name: ThaneGuns
version: ${project.version}
main: org.thane.ThaneGuns
depend: [ProtocolLib, NMSUtils]
authors: [Thane]
description: Adds guns
commands:
  test:
    description: test command.
    usage: /test
